# Generated by Django 3.2.4 on 2021-06-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoRestApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='autorname',
            new_name='authorname',
        ),
    ]
